#Properties for the Autograder
#Mon Apr 27 17:30:49 CEST 2026
GenerateTestcases=false
PrintAllTests=true
ResultOutputDir=./testfiles/results/
SaveTestcases=true
OverwriteTestcases=false
SolutionInputDir=./testfiles/Teacher/Aufgabenblatt2
Testcases=./testfiles/testcases
ToTestInputDirs=./testfiles/students
