#Properties for the Autograder
#Mon Apr 27 17:30:49 CEST 2026
GenerateTestcases=True
PrintAllTests=True
ResultOutputDir=./src/testfiles/results/
SaveTestcases=True
SolutionInputDir=./src/testfiles/Teacher/Aufgabenblatt2
Testcases=./src/testfiles/testcases
ToTestInputDirs=./src/testfiles/students
