#Properties for the Autograder
#Mon Apr 27 17:30:49 CEST 2026
GenerateTestcases=false
PrintAllTests=true
ResultOutputDir=./EP1Test/results/1200
SaveTestcases=true
OverwriteTestcases=false
SolutionInputDir=./EP1Test/solutions/1200
Testcases=./EP1Test/testcases/1200
ToTestInputDirs=./EP1Test/Abgabe_Test_2026_06_16_Slot_12_00
DelimiterCSV=#